server:
  port: 8081

spring:
  datasource:
    #    url: jdbc:h2:~/test
    #    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/naknak?serverTimezone=Asia/Seoul
    password: 7818
  kafka:
    bootstrap-servers:
      localhost:9092
    consumer:
      # consumer bootstrap servers가 따로 존재하면 설정
      # bootstrap-servers: 192.168.0.4:9092

      # 식별 가능한 Consumer Group Id
      group-id: loggroup,loggroup2
      # Kafka 서버에 초기 offset이 없거나, 서버에 현재 offset이 더 이상 존재하지 않을 경우 수행할 작업을 설정
      # latest: 가장 최근에 생산된 메시지로 offeset reset
      # earliest: 가장 오래된 메시지로 offeset reset
      # none: offset 정보가 없으면 Exception 발생
      auto-offset-reset: earliest
      # 데이터를 받아올 때, key/value를 역직렬화
      # JSON 데이터를 받아올 것이라면 JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: =*
      #producer:
      # producer bootstrap servers가 따로 존재하면 설정
      # bootstrap-servers: 3.34.97.97:9092

      # 데이터를 보낼 때, key/value를 직렬화
      # JSON 데이터를 보낼 것이라면 JsonDeserializer
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      authentication-database: admin
      #username:
      #password:
      database: fisher-log
message:
  topic:
    name: name
    name2: name2