FROM python:3

WORKDIR /

## Install packages
COPY requirements.txt ./
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx
## Copy all src files
COPY . .


RUN pip install -r requirements.txt

#RUN pip install gunicorn


RUN python manage.py migrate

RUN python manage.py collectstatic

EXPOSE 8000

#CMD ["gunicorn", "fish.wsgi", "--bind", "0.0.0.0:8000"]
CMD ["bash", "-c", "python manage.py runserver 0.0.0.0:8000"]