FROM gradle:8.1.1-jdk17 AS builder
WORKDIR /

COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .
COPY src src

RUN chmod +x ./gradlew
RUN ls -la # Check the list of files and their permissions
RUN ./gradlew build


FROM azul/zulu-openjdk:17
COPY --from=builder build/libs/*-SNAPSHOT.jar app.jar

#EXPOSE 8080

ENTRYPOINT ["java",  "-jar", "/app.jar"]

